- hosts: localhost
  vars:
    name_tag: contrail
    build_tag: contrail-buildmachine
  tasks:

  - name: Create a new VPC
    ec2_vpc:
      state: present
      cidr_block: 172.23.0.0/16
      resource_tags:
        Name: k8s-vpc
      region: us-west-2
      internet_gateway: True
      subnets:
        - cidr: 172.23.1.0/24
          az: us-west-2b
      route_tables:
        - subnets:
            - 172.23.1.0/24
          routes:
            - dest: 0.0.0.0/0
              gw: igw
    register: vpc

  - name: Create a new Subnet
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ vpc.vpc_id }}"
      cidr: 172.23.1.0/24
      region: us-west-2
      resource_tags:
        Name: k8s-subnet
    register: subnet

  - name: get my public IP
    ipify_facts:

  - name: Create a new security group
    ec2_group:
      name: K8s security group
      description: It allows ports 22, 80,8080 and 443 in and 80 and 443 out
      vpc_id: "{{vpc.vpc_id}}"
      region: us-west-2
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ipify_public_ip}}/32"
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: all
          group_name: K8s security group
      rules_egress:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: all
          group_name: K8s security group

  - name: Create Build Instance
    ec2:
      
      region: us-west-2
      key_name: k8s-keypair
      instance_type: t2.micro
      image:  ami-efd0428f
      wait: yes
      group: "K8s security group"
      count: 1
      vpc_subnet_id: "{{ subnet.subnet.id }}"
      instance_tags:
        Name: "{{ build_tag }}"
      assign_public_ip: yes
    register: ec2
  - name: Add new instance to build group
    add_host: hostname={{ ec2.instances.0.public_ip }} groupname=build
  - name: Wait for SSH to come up
    wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    with_items: '{{ec2.instances}}'

- hosts: build
  remote_user: ubuntu
  become: true
  gather_facts: no
  tasks:
  pre_tasks:
    - name: install python2 because Ubuntu has python 3
      raw: sudo apt-get -y install python-simplejson

    - name: install git
      apt: name=git state=present

    - name: install python-pip
      apt: name=python-pip state=present

    - name: install ansible
      apt: name=ansible state=present

    - name: install awscli
      apt: name=awscli state=present

    - name: install python-pip
      command: sudo pip install -U boto

    - name: Launch kubeadm in master
      shell: sudo git clone https://github.com/Juniper/contrail-ansible.git
